name: Run Node Setup
run-name: Run Node Setup by ${{ github.actor }} in ${{ inputs.sub-folder }} with ${{ github.event_name }}
on: 
  workflow_dispatch:
    inputs:
      sub-folder:
        description: 'which folder would you like to test? ./frontend or ./backend?'
        default: './frontend'
        type: string
        required: true

jobs: 
  initialize-project:
    uses: a-shevlin/todo-v1/.github/workflows/setup-and-install-node.yml@main
    with:
      sub-folder: ${{ inputs.sub-folder }}
    
  pull-cache-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Check files in github actions
        run: |
          cd
          ls ${{ github.workspace }}
        
      - name: Restore cached package
        id: cached-node-restore
        uses: actions/cache/restore@v3
        with: 
          path: |
            ${{ inputs.sub-folder }}/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('${{ inputs.sub-folder }}/package-lock.json') }}
          
      - name: Check for vite in modules cache
        run: ls ${{ inputs.sub-folder }}/node_modules/.bin | grep vite
        
      - name: Build Dist
        run: |
          cd ${{ inputs.sub-folder }}
          npm run build




#      - name: Create .env File
#        run: |
#          touch .env
#          echo VITE_APP_MAPBOX_TOKEN=${{ secrets.VITE_APP_MAPBOX_TOKEN }} >> .env
