name: Node Setup
run-name: Install NodeJS Modules for ${{ inputs.sub-folder }} called by ${{ github.actor }}.

on: 
  workflow_call:
    inputs:
      sub-folder:
        description: 'descriptor for what is passed down from calling workfrlow'
        default: './frontend'
        type: string
          
jobs:
  check-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          node-version: 18.x
        
      - name: Get Node cache directory
        id: node-cache-dir-path
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
        
      - name: Print ${{steps.node-cache-dir-path.outputs.dir}}
        run: echo "This is a test ;)"

      - name: Cache Node Package
        id: node-cache
        uses: actions/cache@v3
        with: 
          path: ${{ inputs.sub-folder }}/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('${{ inputs.sub-folder }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-
          
      - name: Install dependencies if necessary
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          cd ${{ inputs.sub-folder }}
          npm ci
